cd source
..\bin\Poc BaseSys.mod
..\bin\Poc Crypt.mod
..\bin\Poc Scanner.mod
..\bin\Poc Base.mod
..\bin\Poc Generator.mod
..\bin\Poc Parser.mod
..\bin\Poc Poc.mod
cd ..
cd lib
..\bin\Poc Rtl.mod
